name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: '>=6'
        run_install: |
          - args: [--frozen-lockfile, --no-verify-store-integrity]
    - name: Test
      run: npm test
    - name: Coverage
      run: npm run coverage
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
